### ISSUE TITLE
Error when starting the discord bot

### ISSUE THREAD

**Issue by King-BR** [Jinzulen/DEmojiJS#8] opened 2020-07-04 18:16 UTC
Everytime i start my bot it show this error

![image](https://user-images.githubusercontent.com/51011050/86518704-b3475100-be09-11ea-8abc-c8ebdc4f1b0f.png)

**Comment by Jinzulen** [comment] 2020-07-05 11:37
@King-BR Ah. I figured this wouldn't be an issue for now, DiscordEmoji have re-branded into [Emoji.gg](https://emoji.gg/), so the API endpoints have changed.

I'm going to issue an update shortly.

**Comment by King-BR** [comment] 2020-07-05 16:05
The most strange thing is that when i try to request with the same URL on the browser It works just fine

**Comment by Pneuma00** [comment] 2020-11-07 06:51
I have the same issue too. Is there new version that doesn't have the issue?

**Comment by King-BR** [comment] 2020-11-07 17:50
@Pneuma714 he didnt fixed it yet. But you can install a fixed version i made using `npm install King-BR/DEmojiJS#patch-1`

**Comment by Jinzulen** [comment] 2020-11-07 20:26
@King-BR @Pneuma714 I apologize, I have been ridiculously busy these past few months so I had no chance to tend to this, you will be pleased to know that I've fixed this and once I'm through running a few tests to ensure everything is running as it should, I will push the patch.

**Comment by Jinzulen** [comment] 2020-11-07 20:38
@King-BR @Pneuma714 The patch has been pushed and the problem is resolved as of DEmojiJS v1.3.6. I will be closing this issue, please create a new issue if you encounter any new problems and I will try to tend to them as soon as I'm able.

**Closed as completed by Jinzulen** 2020-11-07 20:38 UTC
Labels: bug
